kind: pipeline
type: kubernetes
name: openvpn-exporter

steps:
- name: build-image
  image: plugins/kaniko
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: adamkoro/openvpn-exporter
    tags:
    - latest
    - ${DRONE_COMMIT_SHA:0:7}